spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        follower_channel:
          name: follower_channel
        profile_view_channel:
          name: profile_view_channel

server:
  port: 8080

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082

payment-service:
  host: localhost
  port: 9080

aws:
  accessKey: accessKey
  secretKey: secretKey
  region: region

services:
  s3:
    bucket-name: user_bucket
    isMocked: true
  avatar:
    avatar-prefix: avatar
    small-avatar-prefix: small_avatar
    small-file-width: 200
    small-file-height: 200
    seed-range: 20000

dice-bear:
  url: https://api.dicebear.com
  version: 9.x
  file-type: jpeg
  generation-param: seed
  styles: >
    adventurer-neutral, 
    adventurer, 
    big-ears-neutral, 
    big-ears, 
    pixel-art