spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
  profiles:
    active: local

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        follower_channel:
          name: follower_channel
        profile_view_channel:
          name: profile_view_channel
        mentorship_requested_channel:
          name: mentorship_requested_channel

        recommendation_received:
          name: recommendation_received_channel

        mentorship_accepted_channel:
          name: mentorship_accepted_channel
        recommendation_channel:
          name: recommendation_channel
        recommendation_requested:
          name: recommendation_requested_channel
        mentorship_offered_channel:
          name: mentorship_offered_channel
        profile_pic_channel:
          name: profile_pic_channel

server:
  port: 8080

project-service:
  host: localhost
  port: 8082

payment-service:
  host: localhost
  port: 9080

aws:
  accessKey: access_key
  secretKey: secret_key
  region: bucket_region

services:
  s3:
    endpoint: http://127.0.0.1:9000
    accessKey: user
    secretKey: password
    bucketName: corpbucket
    isMocked: true

premium:
  removal:
    scheduled:
      cron: "0 0 10 * * MON"
    batchSize:
      size: 100
async:
  core-pool-size: 5
  max-pool-size: 50
  queue-capacity: 100

dicebear:
  avatar:
    styles: "adventurer,adventurer-neutral,avataaars,avataaars-neutral,big-ears,big-ears-neutral,big-smile,bottts,bottts-neutral,croodles,croodles-neutral,dylan,micah,fun-emoji,lorelei,lorelei-neutral,notionists,notionists-neutral,micah,miniavs,open-peeps,personas,pixel-art,pixel-art-neutral"
    base-url: "https://api.dicebear.com/9.x/"
    style-path: "/{style}/svg"