spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        follower_channel:
          name: follower_channel
        profile_view_channel:
            name: profile_view_channel

  servlet:
    multipart:
      max-file-size: 5MB

server:
  port: 8080

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082

payment-service:
  host: localhost
  port: 9080

aws:
  accessKey: "8hzEe6m0CHClRlZudZ6l"
  secretKey: "qXXnIDz2CUW0eXReb6Ghb77guwmnXL3OLzEGe5KQ"
  region: "http://127.0.0.1:9000/"

services:
  s3:
    bucket-name: user-bucket
    isMocked: true

springfox.documentation.swagger.v2.path: /api-docs