app:
  max-active-user-goals: 3

spring:
  mvc:
    servlet:
      path: /api/v1
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        mentorship-channel:
          name: mentorship_channel
        follower-event-channel:
          name: follower_event

services:
  s3:
    endpoint: http://127.0.0.1:9000
    accessKey: user
    secretKey: password
    bucketName: corpbucket
    max-image-size-mb: 5

server:
  port: 8080

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082

payment-service:
  host: localhost
  port: 9080

scheduler:
  clear-events:
    cron: "0 0 0 * * SUN"
    batchSize: 10

executorConfig:
  thread-pool-size: 10

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        recommendation_channel:
          name: recommendation_channel
premium:
  removal:
    batch-size: 100
    thread-pool:
      core-pool-size: 8
      max-pool-capacity: 16
      queue-capacity: 32
    interval: "@weekly"

data:
  redis:
    port: 6379
    host: localhost
    channels:
      recommendation_channel:
        name: recommendation_channel
      mentorship_requested_channel:
        name: mentorship_requested_channel
      goal_completed_channel:
        name: goal_completed_channel