spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        mentorship-channel:
          name: mentorship_channel
        follower-event-channel:
          name: follower_event
  cloud:
    openfeign:
      client:
        config:
          DiceBear:
            connectTimeout: 5000
            readTimeout: 10000
services:
  user-service:
    name: User service

  payment-service:
    host: localhost
    port: 9080

  project-service:
    host: localhost
    port: 8082

  s3:
    endpoint: http://127.0.0.1:9000
    accessKey: user
    secretKey: password
    region: us-east-1
    bucketName: userbucket

server:
  port: 8080

logging:
  level:
    root: info

profile-picture:
  normal:
    path: image/default-profile-picture.svg
    size: 320
  small:
    path: image/default-small-profile-picture.svg
    size: 110