spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        event-starter: event_starter_channel
        profile-view: profile-view_channel
        mentorship-channel:
          name: mentorship_channel
        follower-event-channel:
          name: follower_event

server:
  port: 8080

scheduler:
  clear-events-cron: "@weekly"
  event-batch-size: 100
  thread-pool-size: 4

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082

payment-service:
  host: localhost
  port: 9080

springdoc:
  swagger-ui:
    enabled: true
    url: openapi.yml

premium:
  scheduled:
    weekly: "0 0 0 * * MON"
  pool-size: 3
  batch-size: 100