spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        mentorship-channel:
          name: mentorship_channel
        follower-event-channel:
          name: follower_event

server:
  port: 8080

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082

payment-service:
  host: localhost
  port: 9080
  base-path: /api
  url: http://${payment-service.host}:${payment-service.port}${payment-service.base-path}

app:
  promotion:
    user_views_decrement_schedule_time: 10000
    event_views_decrement_schedule_time: 10000
    scheduled_decrement_pool_size: 2
  retryable:
    payment_service:
      send_payment:
        max_attempts: 3
        delay: 100
        multiplier: 2
    event_promotion_repository_batch:
      update_event_promotion:
        max_attempts: 3
        delay: 100
        multiplier: 2
    user_promotion_repository_batch:
      update_user_promotion:
        max_attempts: 3
        delay: 100
        multiplier: 2


