spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        follower_channel:
          name: follower_channel
        profile_view_channel:
          name: profile_view_channel
        analytic_channel:
          name: analytics_channel
        user_events_channel:
          name: user_events_channel
        premium_events_channel:
          name: premium_events_channel
        project_events_channel:
          name: project_events_channel
        user_ban_channel:
          name: user_ban_channel
        started_events_channel:
          name: started_events_channel
        mentorship_channel:
          name: mentorship_channel

server:
  port: 8080

logging:
  level:
    root: info
    org.springframework.retry: DEBUG

project-service:
  host: localhost
  port: 8082

payment-service:
  host: localhost
  port: 9080
  endpoint: /api/payment
  retry:
    max-attempts: 5
    delay-ms: 3000

aws:
  accessKey: your-access-key
  secretKey: your-secret-key
  bucketName: your-bucket-name
  region: your-region

services:
  s3:
    bucket-name: corpx-unicorn-dicebear-bucket
    isMocked: true

google:
  calendar:
    scopes: https://www.googleapis.com/auth/calendar
    application-name: Corporation-X
    tokens-path: tokens
    calendar-id: primary
    access-type: offline
    client-email: serhii.rubets@gmail.com

profile-picture-service:
  styles:
    - adventurer
    - adventurer-neutral
    - avataaars
    - avataaars-neutral
    - big-ears
    - big-ears-neutral
    - big-smile
    - bottts
    - bottts-neutral
    - croodles
    - croodles-neutral
    - fun-emoji
    - icons
    - identicon
    - initials
    - lorelei
    - lorelei-neutral
    - micah
    - miniavs
    - notionists
    - notionists-neutral
    - open-peeps
    - personas
    - pixel-art
    - pixel-art-neutral
    - shapes
    - thumbs
  dicebear:
    baseUrl: "https://api.dicebear.com/6.x/"
  image:
    resized-dimensions:
      width: 180
      height: 180
  extensions:
    original: ".svg"
    resized: "_small.jpg"