spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        follower_channel:
          name: follower_channel
        profile_view_channel:
          name: profile_view_channel
        search_appearance_channel:
          name: search_appearance_channel
  mvc:
    servlet:
      path: /api/v1
      multipart:
        max-file-size: 5MB

cron:

server:
  port: 8080

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082

payment-service:
  host: localhost
  port: 9080

aws:
  accessKey: user
  secretKey: password
  region: http://127.0.0.1:9000

services:
  s3:
    bucket-name: user-service-bucket
    isMocked: true

scheduler:
  batchSize: 10
  deleteEventsCron: "0 0 * * * *"
  deleteUsersCron: "0 0 * * * *"

dicebear:
  pic-base-url-small: https://api.dicebear.com/7.x/bottts/svg?size=64&seed=
  pic-base-url: https://api.dicebear.com/7.x/bottts/svg?size=256&seed=

image:
  pixels:
    bigSize: 1024
    smallSize: 170

springdoc:
  version: "1.0.0"
  swagger-ui:
    url: /api-docs.yaml
    filter: true