application:
  title: User Service Api
  version: 1.0.0

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        follower_channel:
          name: follower_channel
        profile_view_channel:
          name: profile_view_channel
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: 8080

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082

payment-service:
  host: localhost
  port: 9080

aws:
  accessKey: access_key
  secretKey: secret_key
  region: bucket_region

services:
  s3:
    accessKey: user
    secretKey: password
    endpoint: http://127.0.0.1:9000
    bucketName: user-bucket
    maxSizeBytes: 5242880
    smallSize: 170
    largeSize: 1080
    isMocked: true
defaultAvatar:
  url: https://api.dicebear.com/9.x/adventurer/jpg?seed=