spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      topic:
        userBan: user_ban
      channels:
        mentorship-accepted-channel: mentorship_accepted_channel
        follower_channel:
          name: follower_view_channel
        profile_view_channel:
          name: profile_view_channel
        profile_picture_channel:
          name: profile_pic_channel
        mentorship_request_channel:
          name: mentorship_request_channel

server:
  port: 8080

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082

payment-service:
  host: localhost
  port: 9080

aws:
  accessKey: dummy-access-key
  secretKey: dummy-secret-key
  region: eu-north-1

services:
  s3:
    bucket-name: dummy-bucket-name
    isMocked: true
  avatar:
    pattern: avatar_%d.${dice-bear.file-type}
    small-pattern: small_avatar_%d.${dice-bear.file-type}
    small-file-width: 200
    small-file-height: 200
    seed-range: 20000
    content-type: image/jpeg

springfox:
  documentation:
    swagger:
      v2:
       path: /api-docs

dice-bear:
  url: https://api.dicebear.com
  version: 9.x
  file-type: jpeg
  params: seed=%d
  styles: >
    adventurer-neutral, 
    adventurer, 
    big-ears-neutral, 
    big-ears, 
    pixel-art

thread-pool:
  size:
    min: 10
    max: 20
  keep-alive:
    time: 60
    time-unit: SECONDS
  queue-size: 10000