spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
  servlet:
    multipart:
      max-file-size: 10MB

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      jdbc:
        batch_size: 100
      order_inserts: true
      order_updates: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        follower_channel:
          name: follower_channel
        profile_view_channel:
          name: profile_view_channel
        analytic_channel:
          name: analytics_channel

server:
  port: 8080

logging:
  level:
    root: info
    org.springframework.retry: DEBUG

project-service:
  host: localhost
  port: 8082

payment-service:
  host: localhost
  port: 9080
  endpoint: /api/payment
  retry:
    max-attempts: 5
    delay-ms: 3000

aws:
  accessKey: access_key
  secretKey: secret_key
  region: bucket_region

services:
  s3:
    bucket-name: user_backet
    isMocked: true
