spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        follower_channel:
          name: follower_channel
        profile_view_channel:
          name: profile_view_channel
        mentorship_channel:
          name: mentorship_channel

  profiles:
    active: test

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: 8080
  servlet:
    context-path: /api/v1

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082

payment-service:
  host: localhost
  port: 9080

aws:
  accessKey: access_key
  secretKey: secret_key
  region: bucket_region

goals:
  limit:
    max-per-user: 3
  invitations:
    max-per-user: 3

mentorship:
  request:
    time-period-for-single-request: 3

randomAvatar:
  url: https://api.dicebear.com/8.x/pixel-art/jpg?seed=
