spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        follower_channel:
          name: follower_channel
        profile_view_channel:
          name: profile_view_channel

server:
  port: 8080

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082

payment-service:
  host: localhost
  port: 9080

services:
  s3:
    accessKey: accessKey
    secretKey: secretKey
    bucketName: caveri-testing-backet
    region: us-east-1

  diceBear:
    avatarUrl:
      url: https://api.dicebear.com/9.x/
      fullPostfix: /svg?seed=
      smallPostfix: /svg?size=${services.diceBear.avatarUrl.size}&seed=
      size: 32
    styles:
      - adventurer
      - adventurer-neutral
      - avataaars
      - avataaars-neutral
      - big-ears
      - big-ears-neutral
      - big-smile
      - bottts
      - bottts-neutral
      - croodles
      - croodles-neutral
      - dylan
      - fun-emoji
      - glass
      - icons
      - identicon
      - initials
      - lorelei
      - lorelei-neutral
      - micah
      - miniavs
      - notionists
      - notionists-neutral
      - open-peeps
      - personas
      - pixel-art
      - pixel-art-neutral
      - rings
      - shapes
      - thumbs

