openapi: 3.0.3
info:
  title: User Service
  description: User service API
  version: 1.0.0
  termsOfService: 'https://swagger.io/terms'
servers:
    - url: http://localhost:{port}/{basePath}
      description: Local server
      variables:
        port:
          enum:
          - '8080'
          - '8081'
          default: '8080'
        basePath:
          default: api/v1
paths:
  /mentorship/mentors/{id}:
    $ref: 'mentorship/mentors_x.yaml'
  /mentorship/mentees/{id}:
    $ref: 'mentorship/mentees_x.yaml'
  /mentorship/mentors:
    $ref: 'mentorship/mentors.yaml'
  /mentorship/mentees:
    $ref: 'mentorship/mentees.yaml'
