name: CI

run-name: by @${{ github.actor }}

on: [push]

jobs:
  build:
    name: build and test project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Run tests with Gradle
        run: ./gradlew test --no-daemon