name: ci

on:
  pull_request:
    branches:
      - 'phoenix-master-bc4'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Tests
        run: ./gradlew test