name: CI

on:
    pull_request:
        branches: [ feature/pipeline-BC-3806 ]

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up JDK 17
          uses: actions/setup-java@v2
          with:
            java-version: 17
            distribution: 'adopt'

        - name: Build Gradle
          run: ./gradlew build

        - name: Run tests
          run: ./gradlew test

  #      - name : Upload coverage to Codecov
   #       uses: codecov/codecov-action@v1
    #      with:
     #       token: ${{ secrets.CODECOV_TOKEN }}