name: Java CI with Gradle (Cerberus)

on:
  push:
    branches:
      - feature/pipline-BC-1634
  pull_request:
    branches:
      - feature/pipline-BC-1634


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '21'
    - run: ./gradlew build --no-daemon
