name: ci

on:
  pull_request:
    branches:
      - 'feature/pipline-BC-BJS2-6440'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Tests
        run: ./gradlew test
