name: Java CI with Gradle

on:
  pull_request:
    branch:
      unicorn-master

jobs:
  build_and_run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v1.4.4
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Build and Run Tests with Gradle
        run: |
          ./gradlew build --no-daemon &&
          ./gradlew test --no-daemon